JAVAC = /usr/lib/jdk1.6.0_04/bin/javac
JAR = /usr/lib/jdk1.6.0_04/bin/jar
PACKAGE = ailibrary.ge.general

all: $(PACKAGE)

ailibrary.ge.general:
	$(JAVAC) *.java
	$(JAR) cfv ailibrary.ge.general.jar *.class


