
JAVAC = /usr/lib/jdk1.6.0_04/bin/javac
JAR = /usr/lib/jdk1.6.0_04/bin/jar
PACKAGE = ailibrary.ge.grammar.varexp

all: $(PACKAGE)

ailibrary.ge.grammar.varexp:
	$(JAVAC) -sourcepath ../../../../ *.java
	$(JAR) cfv ailibrary.ge.grammar.varexp.jar *.java




